name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: static

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write  # Permissions to deploy to GitHub Pages
      id-token: write  # To verify the deployment originates from an authorized source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
